In [3]:
project_root = "U:/ML_project/Bargh_ML"
import pandas as pd
import os

In [10]:
csv_semi_processed_path = os.path.join(project_root, "data", "interim", f"weather.csv")
df1 = pd.read_csv(csv_semi_processed_path, encoding='utf-8')

In [11]:
csv_semi_processed_path = os.path.join(project_root, "data", "interim", f"weather_old.csv")
df2 = pd.read_csv(csv_semi_processed_path, encoding='utf-8')

In [16]:
df1.head(10)

,unitid,date,time,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,surface_pressure,evapotranspiration,wind_speed_10m,wind_direction_10m
0,917,2021-03-22,24,11.046000,40.0,-2.051930,8.177171,0.0,0.0,0.0,845.17020,0.0,3.075841,339.443880
1,917,2021-03-23,1,10.746000,40.0,-2.321814,8.073168,0.0,0.0,0.0,845.67957,0.0,1.484318,75.963730
2,917,2021-03-23,2,11.396000,41.0,-1.400991,8.694241,0.0,0.0,0.0,846.35693,0.0,2.545584,81.869990
3,917,2021-03-23,3,13.695999,31.0,-3.143477,10.836497,0.0,0.0,0.0,847.72810,0.0,2.036468,44.999897
4,917,2021-03-23,4,15.296000,27.0,-3.610290,12.558243,0.0,0.0,0.0,848.38824,0.0,0.804984,333.435030
5,917,2021-03-23,5,17.296000,25.0,-2.933569,14.478645,0.0,0.0,0.0,848.57294,0.0,3.319036,310.601230
6,917,2021-03-23,6,19.095999,24.0,-1.958416,17.564362,0.0,0.0,0.0,848.64300,0.0,3.096837,324.462250
7,917,2021-03-23,7,21.196000,23.0,-0.767929,19.919110,0.0,0.0,0.0,849.18585,0.0,4.349896,294.443940
8,917,2021-03-23,8,24.246000,21.0,0.527187,22.804940,0.0,0.0,0.0,849.83980,0.0,10.009036,307.694300
9,917,2021-03-23,9,25.696000,20.0,1.050168,21.795982,0.0,0.0,0.0,849.61420,0.0,23.773632,302.005340

In [18]:
df2.head(10)

,unitid,date,time,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,surface_pressure,evapotranspiration,wind_speed_10m,wind_direction_10m
0,917,2021-03-23,1,11.046000,40.0,-2.051930,8.177171,0.0,0.0,0.0,845.17020,0.0,3.075841,339.443880
1,917,2021-03-23,2,10.746000,40.0,-2.321814,8.073168,0.0,0.0,0.0,845.67957,0.0,1.484318,75.963730
2,917,2021-03-23,3,11.396000,41.0,-1.400991,8.694241,0.0,0.0,0.0,846.35693,0.0,2.545584,81.869990
3,917,2021-03-23,4,13.695999,31.0,-3.143477,10.836497,0.0,0.0,0.0,847.72810,0.0,2.036468,44.999897
4,917,2021-03-23,5,15.296000,27.0,-3.610290,12.558243,0.0,0.0,0.0,848.38824,0.0,0.804984,333.435030
5,917,2021-03-23,6,17.296000,25.0,-2.933569,14.478645,0.0,0.0,0.0,848.57294,0.0,3.319036,310.601230
6,917,2021-03-23,7,19.095999,24.0,-1.958416,17.564362,0.0,0.0,0.0,848.64300,0.0,3.096837,324.462250
7,917,2021-03-23,8,21.196000,23.0,-0.767929,19.919110,0.0,0.0,0.0,849.18585,0.0,4.349896,294.443940
8,917,2021-03-23,9,24.246000,21.0,0.527187,22.804940,0.0,0.0,0.0,849.83980,0.0,10.009036,307.694300
9,917,2021-03-23,10,25.696000,20.0,1.050168,21.795982,0.0,0.0,0.0,849.61420,0.0,23.773632,302.005340

In [24]:
df1['temperature_2m'].values == df2['temperature_2m'].values

ValueError: operands could not be broadcast together with shapes (455156,) (455195,)

In [34]:
df3 = df1.merge(df2, how="inner", on=["date","unitid","time"])

In [35]:
len(df3)

455143

In [36]:
len(df1)

455156

In [37]:
len(df2)

455195

In [40]:
df3[['temperature_2m_x','temperature_2m_y']]

        temperature_2m_x  temperature_2m_y
0              10.746000         11.046000
1              11.396000         10.746000
2              13.695999         11.396000
3              15.296000         13.695999
4              17.296000         15.296000
...                  ...               ...
455138         18.531000         19.681000
455139         16.831000         18.531000
455140         17.531000         16.831000
455141         16.980999         17.531000
455142         16.531000         16.980999

[455143 rows x 2 columns]

In [41]:
df1.columns

Index(['unitid', 'date', 'time', 'temperature_2m', 'relative_humidity_2m',
       'dew_point_2m', 'apparent_temperature', 'precipitation', 'rain',
       'snowfall', 'surface_pressure', 'evapotranspiration', 'wind_speed_10m',
       'wind_direction_10m'],
      dtype='object')