<h1>
    This file shows which units are not in the final df becase of lack of data.
</h1>

In [28]:
import os
import sys

current_dir = os.getcwd()
project_root = current_dir[:current_dir.find("src") - 1]
sys.path.insert(0, project_root)
from src.models.train_model.train_model import *

In [29]:
df_old = pd.read_csv(os.path.join(project_root, "data", "processed", "integrated.csv"))
df_new = pd.read_csv(os.path.join(project_root, "data", "processed", "semi_processed.csv"))
df_energy = pd.read_csv(os.path.join(project_root, "data", "interim", "energy.csv"))
df_commitment = pd.read_csv(os.path.join(project_root, "data", "interim", "commitment.csv"))
df_factors = pd.read_csv(os.path.join(project_root, "data", "interim", "factors.csv"))
df_selleroffer = pd.read_csv(os.path.join(project_root, "data", "interim", "selleroffer.csv"))

In [106]:
nc_old = df_old[["id","name","code"]].drop_duplicates()
nc_new = df_new[["id","name","code"]].drop_duplicates()
nc_energy = df_energy[["DispPlantCode","Name","UnitCode"]].drop_duplicates().rename(columns={"DispPlantCode":"id","UnitCode":"code"})
nc_commitment = df_commitment[["PowerPlantCode","PowerPlantName","UnitCode"]].drop_duplicates().rename(columns={"PowerPlantCode":"id","UnitCode":"code"})
nc_factors = df_factors[["PowerPlantCode","PowerPlantName","UnitCode"]].drop_duplicates().rename(columns={"PowerPlantCode":"id","UnitCode":"code"})
nc_selleroffer = df_selleroffer[["PowerPlantCode","PowerPlantName","UnitCode"]].drop_duplicates().rename(columns={"PowerPlantCode":"id","UnitCode":"code"})

In [107]:
len(nc_old), len(nc_commitment), len(nc_factors), len(nc_selleroffer), len(nc_energy), len(nc_new)

(108, 108, 72, 108, 98, 72)

In [108]:
def set_minus(df1, df2, column=None):
    if column is None:
        column = df1.columns.to_list()
    merged = df1.merge(df2, on=column, how='left', indicator=True)
    result = merged[merged['_merge'] == 'left_only'].drop('_merge', axis=1)
    return result

In [109]:
set_minus(nc_commitment, nc_old, column=["id","code"])

Empty DataFrame
Columns: [id, PowerPlantName, code, name]
Index: []

In [110]:
set_minus(nc_factors, nc_old, column=["id","code"])

Empty DataFrame
Columns: [id, PowerPlantName, code, name]
Index: []

In [111]:
set_minus(nc_selleroffer, nc_old, column=["id","code"])

Empty DataFrame
Columns: [id, PowerPlantName, code, name]
Index: []

In [112]:
set_minus(nc_energy, nc_old, column=["id","code"])

     id                     Name code name
44  365  سيکل ترکيبي شهداي پيروز  G13  NaN
45  365  سيکل ترکيبي شهداي پيروز  G14  NaN
47  365  سيکل ترکيبي شهداي پيروز   S2  NaN

In [113]:
df_old_to_new = set_minus(nc_old, nc_new, column=["id","code"])

In [114]:
df_old_to_new[df_old_to_new["code"].str.startswith("G")]

Empty DataFrame
Columns: [id, name_x, code, name_y]
Index: []

In [115]:
df_new_good = df_new[df_new["is_good_peak"] >= 4]

In [116]:
nc_new_good = df_new_good[["id","name","code"]].drop_duplicates()

In [117]:
len(nc_new_good),len(nc_new)

(71, 72)

In [118]:
set_minus(nc_new, nc_new_good, column=["id","code"])

     id           name_x code name_y
32  636  سیکل ترکیبی یزد  G13    NaN