In [2]:
import UnitGenerationPredictor as ugp

In [3]:
ugp.train_model()

2026-01-14 10:36:36 - src.models.train_model.train_model - INFO -
****************
train models on normal data:
2026-01-14 10:36:40 - src.models.train_model.train_model - INFO - Rows with goodness=5 have been selected
2026-01-14 10:36:40 - src.models.train_model.train_model - INFO - Features have been selected successfully
2026-01-14 10:36:40 - src.models.train_model.train_model - INFO - Train and test data related to جنوب اصفهان - چهلستون_G11:
2026-01-14 10:36:40 - src.models.train_model.train_model - INFO - Train rmse error: 1.904% , Size of data: 729
2026-01-14 10:36:40 - src.models.train_model.train_model - INFO - Train and test data related to جنوب اصفهان - چهلستون_G12:
2026-01-14 10:36:40 - src.models.train_model.train_model - INFO - Train rmse error: 1.605% , Size of data: 450
2026-01-14 10:36:40 - src.models.train_model.train_model - INFO - Train and test data related to جنوب اصفهان - چهلستون_G13:
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train rmse error: 2.485% , Size of data: 580
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train and test data related to جنوب اصفهان - چهلستون_G14:
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train rmse error: 2.036% , Size of data: 381
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train and test data related to جنوب اصفهان - چهلستون_G15:
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train rmse error: 1.993% , Size of data: 431
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train and test data related to جنوب اصفهان - چهلستون_G16:
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train rmse error: 1.640% , Size of data: 519
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train and test data related to حافظ_G11:
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train rmse error: 1.576% , Size of data: 794
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train and test data related to حافظ_G12:
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train rmse error: 1.846% , Size of data: 599
2026-01-14 10:36:41 - src.models.train_model.train_model - INFO - Train and test data related to حافظ_G13:
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train rmse error: 2.396% , Size of data: 487
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train and test data related to حافظ_G14:
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train rmse error: 1.862% , Size of data: 561
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train and test data related to حافظ_G15:
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train rmse error: 1.883% , Size of data: 542
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train and test data related to حافظ_G16:
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train rmse error: 2.011% , Size of data: 430
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train and test data related to سبلان_G11:
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train rmse error: 3.144% , Size of data: 1050
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train and test data related to سبلان_G12:
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train rmse error: 1.319% , Size of data: 813
2026-01-14 10:36:42 - src.models.train_model.train_model - INFO - Train and test data related to سبلان_G13:
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train rmse error: 2.287% , Size of data: 466
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train and test data related to سبلان_G14:
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train rmse error: 1.362% , Size of data: 366
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train and test data related to سبلان_G15:
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train rmse error: 1.970% , Size of data: 561
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train and test data related to سبلان_G16:
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train rmse error: 2.335% , Size of data: 465
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی ارومیه_G11:
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train rmse error: 1.913% , Size of data: 593
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی ارومیه_G12:
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train rmse error: 2.328% , Size of data: 682
2026-01-14 10:36:43 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی ارومیه_G13:
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train rmse error: 2.760% , Size of data: 538
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی ارومیه_G14:
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train rmse error: 1.691% , Size of data: 646
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی ارومیه_G15:
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train rmse error: 2.407% , Size of data: 495
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی ارومیه_G16:
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train rmse error: 1.699% , Size of data: 607
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G11:
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train rmse error: 1.133% , Size of data: 986
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G12:
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train rmse error: 1.109% , Size of data: 466
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G13:
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train rmse error: 1.498% , Size of data: 618
2026-01-14 10:36:44 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G14:
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train rmse error: 1.941% , Size of data: 540
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G15:
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train rmse error: 1.462% , Size of data: 418
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G16:
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train rmse error: 1.067% , Size of data: 718
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی یزد_G11:
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train rmse error: 1.386% , Size of data: 484
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی یزد_G12:
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train rmse error: 1.728% , Size of data: 266
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی یزد_G14:
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train rmse error: 1.698% , Size of data: 134
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی یزد_G15:
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train rmse error: 1.086% , Size of data: 187
2026-01-14 10:36:45 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی یزد_G16:
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train rmse error: 1.579% , Size of data: 374
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G11:
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train rmse error: 1.435% , Size of data: 735
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G12:
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train rmse error: 2.148% , Size of data: 331
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G13:
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train rmse error: 1.954% , Size of data: 234
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G14:
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train rmse error: 2.416% , Size of data: 324
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G15:
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train rmse error: 1.609% , Size of data: 503
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G16:
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train rmse error: 1.736% , Size of data: 637
2026-01-14 10:36:46 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G17:
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train rmse error: 2.358% , Size of data: 364
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G18:
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train rmse error: 1.830% , Size of data: 628
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G19:
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train rmse error: 1.357% , Size of data: 528
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G20:
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train rmse error: 1.918% , Size of data: 412
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G21:
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train rmse error: 2.502% , Size of data: 314
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G22:
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train rmse error: 1.515% , Size of data: 104
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پیروز - بهبهان_G11:
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train rmse error: 2.517% , Size of data: 564
2026-01-14 10:36:47 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پیروز - بهبهان_G12:
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train rmse error: 2.824% , Size of data: 378
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train and test data related to عسلویه_G11:
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train rmse error: 1.727% , Size of data: 401
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train and test data related to عسلویه_G12:
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train rmse error: 3.214% , Size of data: 153
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train and test data related to عسلویه_G13:
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train rmse error: 1.613% , Size of data: 264
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train and test data related to عسلویه_G14:
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train rmse error: 1.580% , Size of data: 320
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train and test data related to عسلویه_G15:
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train rmse error: 1.527% , Size of data: 392
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train and test data related to عسلویه_G16:
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train rmse error: 1.741% , Size of data: 380
2026-01-14 10:36:48 - src.models.train_model.train_model - INFO - Train and test data related to قم_G11:
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train rmse error: 1.517% , Size of data: 904
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train and test data related to قم_G12:
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train rmse error: 1.255% , Size of data: 461
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train and test data related to قم_G13:
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train rmse error: 1.626% , Size of data: 426
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train and test data related to قم_G14:
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train rmse error: 1.364% , Size of data: 505
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train and test data related to پرند_G11:
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train rmse error: 1.609% , Size of data: 716
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train and test data related to پرند_G12:
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train rmse error: 1.491% , Size of data: 317
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train and test data related to پرند_G13:
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train rmse error: 1.349% , Size of data: 551
2026-01-14 10:36:49 - src.models.train_model.train_model - INFO - Train and test data related to پرند_G14:
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train rmse error: 1.404% , Size of data: 616
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train and test data related to پرند_G15:
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train rmse error: 1.433% , Size of data: 621
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train and test data related to پرند_G16:
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train rmse error: 1.767% , Size of data: 600
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train and test data related to گیلان_G11:
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train rmse error: 1.972% , Size of data: 948
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train and test data related to گیلان_G12:
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train rmse error: 1.971% , Size of data: 488
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train and test data related to گیلان_G13:
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train rmse error: 2.060% , Size of data: 446
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train and test data related to گیلان_G14:
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train rmse error: 2.073% , Size of data: 356
2026-01-14 10:36:50 - src.models.train_model.train_model - INFO - Train and test data related to گیلان_G15:
2026-01-14 10:36:51 - src.models.train_model.train_model - INFO - Train rmse error: 2.298% , Size of data: 228
2026-01-14 10:36:51 - src.models.train_model.train_model - INFO - Train and test data related to گیلان_G16:
2026-01-14 10:36:51 - src.models.train_model.train_model - INFO - Train rmse error: 1.582% , Size of data: 497
2026-01-14 10:36:51 - src.models.train_model.train_model - INFO - Weighted train error: 1.820
2026-01-14 10:36:51 - src.models.train_model.train_model - INFO -
****************
train models on turbo data:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Rows with goodness=6 have been selected
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Features have been selected successfully
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G11:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train rmse error: 1.061% , Size of data: 291
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G12:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train rmse error: 1.096% , Size of data: 147
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G13:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train rmse error: 0.738% , Size of data: 231
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G14:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train rmse error: 0.694% , Size of data: 299
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G15:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train rmse error: 0.931% , Size of data: 213
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی شیروان_G16:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train rmse error: 1.098% , Size of data: 224
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی یزد_G14:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train rmse error: 0.640% , Size of data: 376
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی یزد_G15:
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train rmse error: 1.059% , Size of data: 210
2026-01-14 10:36:54 - src.models.train_model.train_model - INFO - Train and test data related to سیکل ترکیبی یزد_G16:
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train rmse error: 0.642% , Size of data: 569
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G11:
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train rmse error: 0.681% , Size of data: 730
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G12:
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train rmse error: 0.697% , Size of data: 482
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G13:
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train rmse error: 0.648% , Size of data: 338
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G14:
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train rmse error: 0.833% , Size of data: 289
2026-01-14 10:36:55 - src.models.train_model.train_model - INFO - Train and test data related to شهدای پاکدشت - دماوند_G15:

In [3]:
import pandas as pd

In [4]:
a = [["A", 1], ["B", 2]]

df = pd.DataFrame(a, columns=["col1", "col2"])

In [5]:
df

  col1  col2
0    A     1
1    B     2

In [6]:
df.columns = ["AAA", "BBB"]

In [7]:
df

  AAA  BBB
0   A    1
1   B    2

In [10]:
import os,root
df = pd.read_csv(os.path.join(root.get_root(), "data", "processed", f"integrated.csv"))

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1592016 entries, 0 to 1592015
Data columns (total 25 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Unnamed: 0            1592016 non-null  int64
 1   id                    1592016 non-null  int64
 2   name                  1592016 non-null  object
 3   code                  1592016 non-null  object
 4   date                  1592016 non-null  object
 5   hour                  1592016 non-null  int64
 6   required              1592016 non-null  float64
 7   temperature           1586916 non-null  float64
 8   humidity              1586916 non-null  float64
 9   dew                   1586916 non-null  float64
 10  apparent_temperature  1586916 non-null  float64
 11  precipitation         1586816 non-null  float64
 12  rain                  1586816 non-null  float64
 13  snow                  1586816 non-null  float64
 14  surface_pressure      1586916 non-null  float64
 15  evapotranspiration    1592016 non-null  float64
 16  wind_speed            1586916 non-null  float64
 17  wind_direction        1586916 non-null  float64
 18  load_level            1592016 non-null  object
 19  forecasted_load       1592016 non-null  int64
 20  generation            1437638 non-null  float64
 21  declared              1572432 non-null  float64
 22  status                1591934 non-null  object
 23  scadaf                1404511 non-null  float64
 24  temp_sens             1223914 non-null  float64
dtypes: float64(16), int64(4), object(5)
memory usage: 303.7+ MB