In [2]:
import numpy as np

import UnitGenerationPredictor as ugp

In [3]:
ugp.train_model()

2026-01-15 14:03:52 - src.models.train_model.train_model - INFO -
****************
train models on normal data:

KeyboardInterrupt:

In [5]:
import pandas as pd

In [6]:
a = [["A", 1], ["B", 2]]

df = pd.DataFrame(a, columns=["col1", "col2"])

In [7]:
df

  col1  col2
0    A     1
1    B     2

In [8]:
df.columns = ["AAA", "BBB"]

In [9]:
df

  AAA  BBB
0   A    1
1   B    2

In [2]:
import os,root
import pandas as pd
df = pd.read_csv(os.path.join(root.get_root(), "data", "processed", f"integrated.csv"))

In [11]:
df["hour"].drop_duplicates()

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
Name: hour, dtype: int64

In [21]:
import numpy as np

In [22]:
np.unique(df[(df["name"] == "سیکل ترکیبی یزد") & (df["code"] == "G13")]["status"].values,return_counts=True)

(array(['FO', 'FP', 'LA', 'LF1', 'PB', 'PM'], dtype=object),
 array([  777,    33,    14,     3, 11653,   240]))

In [5]:
df.columns.tolist()

['Unnamed: 0',
 'id',
 'name',
 'code',
 'date',
 'hour',
 'required',
 'temperature',
 'humidity',
 'dew',
 'apparent_temperature',
 'precipitation',
 'rain',
 'snow',
 'surface_pressure',
 'evapotranspiration',
 'wind_speed',
 'wind_direction',
 'load_level',
 'forecasted_load',
 'generation',
 'declared',
 'status',
 'scadaf',
 'temp_sens']

In [4]:
df.head()

,Unnamed: 0,id,name,code,date,hour,required,temperature,humidity,dew,...,evapotranspiration,wind_speed,wind_direction,load_level,forecasted_load,generation,declared,status,scadaf,temp_sens
0,0,104,پرند,G11,2021-03-21,1,131.999,NaN,NaN,NaN,...,0.0,NaN,NaN,L,29288,111.602439,132.0,SO,11.38,12.97
1,1,104,پرند,G11,2021-03-21,2,131.998,NaN,NaN,NaN,...,0.0,NaN,NaN,L,28138,111.128080,132.0,SO,10.32,9.36
2,2,104,پرند,G11,2021-03-21,3,131.998,NaN,NaN,NaN,...,0.0,NaN,NaN,L,27300,111.590074,132.0,SO,11.02,11.95
3,3,104,پرند,G11,2021-03-21,4,131.998,NaN,NaN,NaN,...,0.0,NaN,NaN,L,26788,110.930243,132.0,SO,8.26,8.93
4,4,104,پرند,G11,2021-03-21,5,132.999,NaN,NaN,NaN,...,0.0,NaN,NaN,L,26500,110.927996,133.0,SO,9.90,8.47

In [6]:
for col in df.columns.tolist():
    print(col)

Unnamed: 0
id
name
code
date
hour
required
temperature
humidity
dew
apparent_temperature
precipitation
rain
snow
surface_pressure
evapotranspiration
wind_speed
wind_direction
load_level
forecasted_load
generation
declared
status
scadaf
temp_sens

In [7]:
print(len(df.columns.tolist()
))

25